### ISSUE TITLE
Config File missing

### ISSUE THREAD

**Issue by hendrick22** [kivancgunduz/expiration-date-detection#1]
After setting up the repo, the following message appears when running the main:

`Traceback (most recent call last):
  File "(...)/expiration-date-detection/main.py", line 18, in <module>
    args, cfg_fcos = fcos_cfgs(path)
  File "(...)/expiration-date-detection/FCOS/configs/configs.py", line 39, in fcos_cfgs
    cfg.merge_from_file(args.config_file)
  File "(...)/expiry-date-detection/lib/python3.9/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '(...)/expiration-date-detection/data/configs.yaml'
`

Can you please publish the 'data' folder?

**Comment by reshmaram2000** [comment]
The data folder seems to be missing
